import React from "react";
import { Link } from "react-router-dom";

const Digital_marketing = () => {
  return (
    <div
      style={{ marginTop: "13vh " }}
      className="container-fluid p-0 Digital_marketing"
    >
      <img width={"100%"} src="/src/assets/image/digital.PNG" alt="" />
      <div className="container">
        <h1 data-aos="fade-up" className="text-center">Why Choose Rootlet Solutions For Your Digital Marketing Agency?</h1>
        <p data-aos="fade-up" className="text-center">
          Rootlet Solutions is a comprehensive digital marketing agency. We have
          been serving clients across industries since 2005, offering a wide
          range of services. Our expertise spans various online marketing
          tactics such as search engine optimization (SEO), pay-per-click (PPC)
          ads, Amazon store optimization, copywriting, and conversion rate
          optimization (CRO). Additionally, we specialize in web design and
          development for e-commerce and B2B companies. When it comes to
          choosing a digital marketing agency, trust is key. Partner with a
          company you can rely on.
        </p>
        <div className="row">
          <div className="col-lg-6 col-md-6 col-sm-12">
            <div>
              <h1 data-aos="fade-up">Meet our team of digital marketing experts</h1>
              <p data-aos="fade-up">
                Having a website is not enough for the success of your business
                if it fails to be recognized by search engines. To ensure that
                your site is easily discoverable by customers online, we offer
                comprehensive solutions to elevate your online presence. Our
                services include website design, copywriting, keyword
                optimization, social media management, and more. Partnering with
                us guarantees maximum return on your marketing investment.
              </p>
            </div>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            {" "}
            <img src="/src/assets/image/digi1.png" alt=""   data-aos="fade-down"/>
          </div>
          <h1 data-aos="zoom-in" className="text-center">Experience Proven Results</h1>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <img src="/src/assets/image/digi2.png" alt="" data-aos="fade-down" />
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <div>
              {" "}
              <h1 data-aos="fade-up">We Embrace Honesty & Ethics</h1>
              <p data-aos="fade-up">
                Honesty, integrity, and respect for our clients are the core
                values we stand by at Rootlet Solutions. We don't believe in
                pushing unnecessary services or using a one-size-fits-all
                approach. Our dedication lies in boosting rankings, driving
                traffic and conversions, and maximizing ROI for our clients.
              </p>
            </div>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <div>
              <h1 data-aos="fade-up">Digital Marketing Expertise</h1>
              <p data-aos="fade-up">
                Partnering with a digital marketing company that truly
                understands the digital landscape is crucial. Sadly, many firms
                fail to deliver favorable outcomes. At Rootlet Solutions, our
                strategies are proven to work. In fact, our clients often cover
                their website costs within the first month through the influx of
                new business leads generated by our online marketing and SEO
                efforts.
              </p>
            </div>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <img src="/src/assets/image/digi3.png" alt="" data-aos="fade-down"/>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <img src="/src/assets/image/digi4.png" alt="" data-aos="fade-down"/>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <div>
              <h1 data-aos="fade-up">The Ideal assistance for Successful Internet Marketing</h1>
              <p data-aos="fade-up">
                {" "}
                Selecting Rootlet for digital marketing has several benefits
                that may greatly improve the online visibility and efficacy of
                your company. Because of Rootlet's extensive knowledge of the
                digital marketing space, you can be confident that your
                campaigns are carefully planned and take advantage of the newest
                trends and technology to outperform your rivals. Their specially
                designed tactics are centered on your particular company
                requirements, enabling highly focused and customized marketing
                initiatives that connect with your target market. Rootlet offers
                an integrated strategy to optimize your reach and engagement
                across several platforms, encompassing SEO, social media
                management, content development, and analytics. Furthermore,
                real-time monitoring and optimization are made possible by their
                data-driven approaches, which guarantee that your marketing
                initiatives are always improved for peak performance.
              </p>
            </div>
          </div>
          <h1 data-aos="zoom-in" className="text-center">Our Digital Marketing Expertise</h1>
          <div className="col-lg-12" data-aos="fade-down">
            <div>
              <h3 >SEARCH ENGINE OPTIMIZATION – SEO</h3>
              <p>
                We can help you achieve high rankings in the major search
                engines through careful keyword research and white hat
                practices.
              </p>
            </div>
            <div>
              <h3>SOCIAL MEDIA MARKETING</h3>
              <p>
                Staying connected with your audience is crucial, and social
                media marketing plays a big role in that. We'll work
                independently or side-by-side with you to keep your social
                community engaged.
              </p>
            </div>
            <div>
              <h3>PAY PER CLICK – PPC</h3>
              <p>
                While SEO offers long-term growth, sometimes you need an
                immediate boost. Our PPC campaign ensures that the money you
                spend is put to the very best possible use.
              </p>
            </div>
            <div>
              <h3>VIDEO PRODUCTION</h3>
              <p>There's no better way to get your message across than through video. Engage your audience by telling your story and sharing your mission.</p>
            </div>
            <div>
              <h3>CONTENT WRITING</h3>
              <p>Our content writers know Search Engine Optimization and create great marketing copy that's informative and compelling, pushing your business objectives.</p>
            </div>
            <div><h3>REPUTATION MANAGEMENT</h3>
            <p>Your reputation is everything. Our team of experts can help protect and enhance your online reputation for tangible, long-term results.</p></div>
            <div>
              <h3>CONVERSION OPTIMIZATION</h3>
              <p>Turn more site visitors into customers! Our experts utilize the latest Conversion Optimization techniques to increase the percentage of passive website visitors into active users.</p>
            </div>
            <div><h3>AMAZON MARKETING</h3>
            <p>Getting found on Amazon is not easy! Competition is fierce and thick. We'll help your products get found in this massive marketplace.</p></div>
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <img src="/src/assets/image/digi5.png" alt="" data-aos="fade-down" />
          </div>
          <div className="col-lg-6 col-md-6 col-sm-12">
            <div>
              <h1 data-aos="fade-up">Here's what sets us apart and drives our value</h1>
              <p data-aos="fade-up">
                Our dedication to the work is fueled by our genuine concern for
                one another. We place our trust in our collective knowledge,
                always striving for growth through understanding. With humility,
                we fearlessly venture into uncharted territories, exploring with
                purpose and emerging with impactful solutions. These values
                serve as our compass in every project and partnership, every
                single time.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="cta container-3 container-fluid p-0 m-0">
        <div className="container">
          <div className="row">
            <div className="col-lg-6 col-md-7 ">
              <h2 data-aos="fade-up">Let's Get in Touch</h2>
              <h1 data-aos="fade-up">LET'S TALK ABOUT YOUR BUSINESS IT SERVICES NEEDS</h1>
              <p data-aos="fade-up">Feel free to reach out to us.</p>
            </div>
            <div className="col-lg-6 col-md-5">
              <button data-aos="fade-right">
                <Link to="/Contact">
                  GET IN TOUCH <i className="fa-solid fa-arrow-right"></i>
                </Link>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Digital_marketing;
